### PR TITLE
Use different horizons for different frequency series

### PR DESCRIPTION
**Pull request by rjames6023**
# Summary

The number of forecasts is now dependent on the frequency of the underlying time series:

monthly data (freq = 12): 18 forecasts
quarterly data (freq = 4): 8 forecasts
weekly data (freq = 52): 13 forecasts

The forecast_len variable is a dictionary with keys that are the frequency of the series and values that are the number of forecasts to make. The currently implemented horizons are described in the methodology page.

# Related Issues

N/A

# Checklist
  - [x] The change is tested and works locally.
  - [x] All related issues are referenced.
  - [ ] Blog post included in PR if required e.g. new feature.

### CODE REVIEW

**Comment by sjtrny** [comment]
@rjames6023 I've made a few changes after testing. I noticed this warning though:

```
/forecast_dash/updater/models.py:56: RuntimeWarning: invalid value encountered in sqrt
  limit = 1.645 * (np.sqrt((1 + 2 * s) / len(original_ts)))
```

Could you please check if it's of any concern? I've pushed my changes to this branch. You should be able to fetch/pull the changes in your local Git client.

**Comment by rjames6023** [comment]
@sjtrny yep, i will check this later this week and get back to you.

**Comment by rjames6023** [comment]
> @rjames6023 I've made a few changes after testing. I noticed this warning though:
> 
> ```
> /forecast_dash/updater/models.py:56: RuntimeWarning: invalid value encountered in sqrt
>   limit = 1.645 * (np.sqrt((1 + 2 * s) / len(original_ts)))
> ```
> 
> Could you please check if it's of any concern? I've pushed my changes to this branch. You should be able to fetch/pull the changes in your local Git client.

@sjtrny do you know what series you were running when you saw this error? Tried a handful of series locally but couldn't see the error when running the MLP and RNN models (the  error comes from the seasonality_test function used in these two models codetermine if we should remove seasonality from the raw data).

**Comment by sjtrny** [comment]
> @sjtrny do you know what series you were running when you saw this error?

I just ran the whole update script. I'll see if I can identify the specific model and series combinations causing the issue.

**Comment by sjtrny** [comment]
Looks like it is UK GDP Growth series causing the problem. I printed out some extra info to help debug.

LEN OF SERIES, VALUE OF S, VALUE OF TERM TO BE SQRT
```
17 -0.5481977744632158 -0.005670326407437156
/Users/steve/Dropbox/steve/Documents/GitHub/forecast_dash/updater/models.py:57: RuntimeWarning: invalid value encountered in sqrt
  limit = 1.645 * (np.sqrt((1 + 2 * s) / len(original_ts)))
16 -0.5893837064034267 -0.011172963300428343
/Users/steve/Dropbox/steve/Documents/GitHub/forecast_dash/updater/models.py:57: RuntimeWarning: invalid value encountered in sqrt
  limit = 1.645 * (np.sqrt((1 + 2 * s) / len(original_ts)))
15 -0.594357728157432 -0.012581030420990938
/Users/steve/Dropbox/steve/Documents/GitHub/forecast_dash/updater/models.py:57: RuntimeWarning: invalid value encountered in sqrt
  limit = 1.645 * (np.sqrt((1 + 2 * s) / len(original_ts)))
14 -0.5774319263965904 -0.01106170377094148
/Users/steve/Dropbox/steve/Documents/GitHub/forecast_dash/updater/models.py:57: RuntimeWarning: invalid value encountered in sqrt
  limit = 1.645 * (np.sqrt((1 + 2 * s) / len(original_ts)))
```

Looks like the term to be sqrt-ed is negative. Do you know if this a bug in the seasonality detection or just a precision issue?

**Comment by sjtrny** [comment]
I'm going to merge the changes in so that I we can make progress with the other PR and have created a new issue for the sqrt problem https://github.com/forecastlab/forecast_dash/issues/91

**Pull request merged**
