### PR TITLE
Update cv scores table

### PR DESCRIPTION
**Pull request by ardimirzaei**
# Summary

- Fixed sorting of table by removing the multi-sorting. 
- Added a feature to show relative score by best model. 
- Added a button feature to switch between relative and raw scores for the CV table
- Relative scores show based on the model selected. 

# Related Issues

Addresses Issue #134 and #146

# Checklist
  - [x] The change is tested and works locally.
  - [x] All related issues are referenced.
  - [ ] Blog post included in PR if required e.g. new feature.

### CODE REVIEW

**Comment by ardimirzaei** [comment]
Example of the table:

**Relative Scores**
image

**Raw Scores**
image

**Relative Scores with SES (ZNN) as the selected Model**
image

**Comment by ardimirzaei** [comment]
Sorting may not be working correctly. It appears to render as strings. Large numbers starting with a 1, will sort first. I.e 134234 is before 20.

**Comment by ardimirzaei** [comment]
Rounding using np.round keeps the number as a number, but doesn't pad with zeros at the end. 

image

**Comment by sjtrny** [comment]
1. Instead of buttons how about a [toggle switch, radio buttons etc](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/input/)? At the moment the buttons are a little intrusive. 

image

```
dbc.Switch(
    id="standalone-switch",
    label="This is a toggle switch",
    value=False,
)
```

2. I think we have to go with `sort_action='custom',` on the DataTable and do it server side. This will allow sorting to occur numerically and give us full control over how the numbers are actually presented.

https://dash.plotly.com/datatable/callbacks#backend-paging-with-sorting

**Review by sjtrny — APPROVED** [review]

**Pull request merged**
